# Host to use for canonical URL generation (without trailing slash)
host:

# Header-related options
show_govuk_logo: false
service_name: A guide to WCAG
service_link: /index.html

# Links to show on right-hand-side of header
header_links:
  Overview: /index.html
  All success criteria: /all.html
  Content: /content.html
  Design: /design.html
  Code: /code.html
  Checklist: /checklist.html
  Community: /community.html
footer_links:
  Accessibility statement: /accessibility.html

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: false

# Enable collapsible navigation in the sidebar
collapsible_nav: false

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 4

# Enable hoverable anchor links next to every heading
enable_anchored_headings: false

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

# Show GitHub source/issue/repo links at the bottom of each page
show_contribution_banner: true
github_repo: alphagov/guide-to-wcag
